[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
class = "kitty-dropterm"
command = "kitty --class kitty-dropterm"
margin = 50
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.yazi]
animation = "fromTop"
command = "kitty --class kitty-yazi yazi"
class = "kitty-yazi"
margin = 50
size = "75% 60%"
max_size = "1920px 100%"
lazy = true

[scratchpads.ncmpcpp]
animation = "fromTop"
command = "kitty --class kitty-ncmpcpp ncmpcpp"
class = "kitty-ncmpcpp"
margin = 50
size = "75% 60%"
max_size = "1920px 100%"
lazy = true

[scratchpads.btop]
animation = "fromTop"
command = "kitty --class kitty-btop btop"
class = "kitty-btop"
margin = 50
size = "75% 60%"
max_size = "1920px 100%"
lazy = true

[scratchpads.ipython]
animation = "fromRight"
command = "kitty --class kitty-ipython ipython"
class = "kitty-ipython"
margin = 12
size = "40% 90%"
max_size = "1120px 100%"
unfocus = "hide"
lazy = true
