"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
    # open shell
    { on = [ "<C-s>" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

    # ripdrag
    { on = [ "<C-n>" ], run = '''
        shell 'ripdrag "$@" -nx 2>/dev/null &' --confirm
    ''', desc = "Run drag and drop" },
    { on = [ "<C-m>" ], run = '''
        shell 'ripdrag "$@" -Anx 2>/dev/null &' --confirm
    ''', desc = "Run all drag and drop" },

    # lazygit
    { on = [ "<C-g>" ], run = "shell --block --confirm 'lazygit'", desc = "Run lazygit" },

    # copy to system clipboard
    { on = [ "y" ], run = [ "yank",
        '''
        shell --confirm 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
        '''
    ], desc = "Copy file and to system clipboard" },

    # plugin

    # bookmarks
    { on = [ "m" ],      run = "plugin bookmarks-persistence --args=save",            desc = "Save current position as a bookmark"}, 
    { on = [ "'" ],      run = "plugin bookmarks-persistence --args=jump",            desc = "Jump to a bookmark" },
    { on = [ "b", "d" ], run = "plugin bookmarks-persistence --args=delete",          desc = "Delete a bookmark"}, 
    { on = [ "b", "D" ], run = "plugin bookmarks-persistence --args=delete_all",      desc = "Delete all bookmarks"}, 

    # heyjump
    { on = [ "i" ], run = "plugin searchjump",                 desc = "Search jump"},
    { on = [ "I" ], run = "plugin searchjump --args='autocd'", desc = "Search jump (autocd)"},

    # file-actions
    # { on = [ "e" ], run = "plugin file-actions --args='around '", desc = "Perform actions on selected files"},

    # utils plugin
    # chmod
    { on = [ "c", "m" ], run = "plugin mutils --args='chmod'", desc = "Chmod on selected files"},

    # smart enter
    { on = [ "l" ], run =  "plugin --sync mutils --args='smart_enter'", desc = "Enter the child directory, or open the file"},

    # diff
    { on = [ "c", "i", "c" ], run = "plugin mutils --args='diff'", desc = "Diff the selected with the hovered file(output clipboard)"},
    { on = [ "c", "i", "f" ], run = "plugin mutils --args='diff save'", desc = "Diff the selected with the hovered file(output file)"},
]
