"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
    { on = [ "g", "t" ], run = "cd /tmp",                            desc = "Go to the temp directory" },
    { on = [ "g", "r" ], run = "cd /run/user",                       desc = "Go to the user run directory" },
    { on = [ "g", "." ], run = [ "cd ~/.dotfiles", "hidden toggle" ], desc = "Go to the dotfiles directory" },

    # open shell
    { on = [ "<C-s>" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

    # ripdrag
    { on = [ "<C-n>" ], run = "shell 'ripdrag \"$@\" -nx 2>/dev/null &' --confirm",  desc = "Run drag and drop" },
    { on = [ "<C-m>" ], run = "shell 'ripdrag \"$@\" -Anx 2>/dev/null &' --confirm", desc = "Run all drag and drop" },

    # lazygit
    { on = [ "<C-g>" ], run = "shell --block --confirm 'lazygit'", desc = "Run lazygit" },

    # copy to system clipboard
    { on = [ "y" ], run = [ "yank",
        '''
        shell --confirm 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
        '''
    ], desc = "Copy file and to system clipboard" },

    # plugin
    # bookmarks.yazi
    { on = [ "'", "s" ], run = "plugin bookmarks-persistence --args=save",       desc = "Save current position as a bookmark" },
    { on = [ "'", "a" ], run = "plugin bookmarks-persistence --args=jump",       desc = "Jump to a bookmark" },
    { on = [ "'", "d" ], run = "plugin bookmarks-persistence --args=delete",     desc = "Delete a bookmark" },
    { on = [ "'", "D" ], run = "plugin bookmarks-persistence --args=delete_all", desc = "Delete all bookmarks" },

    # searchjump.yazi
    { on = [ "s" ],          run = "plugin searchjump", desc = "Search jump" },
    { on = [ "S" ],          run = "search rg",         desc = "Search files by name using fd" },
    { on = [ "F" ], run = "search fd",         desc = "Search files by content using ripgrep" },

    # max-preview.yazi
    { on = [ "T" ], run = "plugin max-preview", desc = "Maximize or restore preview" },

    # aktionen.yazi
    { on = [ "e" ], run = "plugin aktionen", desc = "File actions" },

    # chmod.yazi
    { on = [ "c", "m" ], run = "plugin mutils --args='chmod'", desc = "Chmod on selected files" },

    # smart enter
    { on = [ "l" ], run =  "plugin mutils --args='smart_enter'", desc = "Enter the child directory, or open the file" },

    # diff.yazi
    { on = [ "c", "i", "c" ], run = "plugin mutils --args='diff'",      desc = "Diff the selected with the hovered file(output clipboard)" },
    { on = [ "c", "i", "f" ], run = "plugin mutils --args='diff save'", desc = "Diff the selected with the hovered file(output file)" },
]
