"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
    # open shell
    { on = [ "<C-s>" ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

    # ripdrag
    { on = [ "<C-n>" ], run = '''
        shell 'ripdrag "$@" -nx 2>/dev/null &' --confirm
    ''', desc = "Run drag and drop" },
    { on = [ "<C-m>" ], run = '''
        shell 'ripdrag "$@" -Anx 2>/dev/null &' --confirm
    ''', desc = "Run all drag and drop" },

    # lazygit
    { on = [ "<C-g>" ], run = "shell --block --confirm 'lazygit'", desc = "Run lazygit" },

    # copy to system clipboard
    { on = [ "y" ], run = [ "yank",
        '''
        shell --confirm 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list'
        '''
    ], desc = "Copy file and to system clipboard" },

    # plugin

    # bookmarks
    { on = [ "m" ],      run = "plugin bookmarks --args=save",            desc = "Save current position as a bookmark"}, 
	{ on = [ "'" ],      run = "plugin bookmarks --args=jump",            desc = "Jump to a bookmark" },
	{ on = [ "b", "d" ], run = "plugin bookmarks --args=delete",          desc = "Delete a bookmark"}, 
	{ on = [ "b", "D" ], run = "plugin bookmarks --args=delete_all",      desc = "Delete all bookmarks"}, 

    # heyjump
    { on = [ "i" ], run = "plugin keyjump --args='global once'", desc = "Keyjump (Normal mode)"},
    { on = [ "I" ], run = "plugin keyjump --args='global'",      desc = "Keyjump (Global mode)"},
    
    # smart-enter
    { on = [ "l" ], run =  "plugin --sync smart-enter", desc = "Enter the child directory, or open the file"},

    # file-actions
    { on = [ "e" ], run = "plugin file-actions --args='around '", desc= "Perform actions on selected files"},
]
