"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
sort_by        = "natural"
sort_sensitive = true
sort_dir_first = true
show_symlink   = true
mouse_events   = [ "click", "scroll", "touch", "drag" ]

[preview]
max_width     = 2160
max_height    = 3840
image_filter  = "lanczos3"
image_quality = 90

[opener]
edit = [
	{ run = '${EDITOR:=nvim} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]

[plugin]
prepend_previewers = [
	{ mime = "audio/*", run = "exifaudio" },
	{ name = "*.md",    run = "glow" },
	{ name = "*.csv",   run = "miller" },
	{ name = "*.ipynb", run = "rich-preview"},
]
append_previewers = [{ name = "*", run = "hexyl" }]
